version: "3"
services:
  web:
    build: .
    ports:
      - "80:80"
    networks:
      - webnet
    links:
      - mongo
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
    #volumes:
      #- './mongo:/data/db'
networks:
  webnet:

